# -*- coding: utf-8 -*-
"""
从两份手册生成 README.md
--------------------------------------------------------------------------------
README 会把「中文操作手册」与「English Operation Manual」的**完整内容**内联进来，
让 GitHub 项目首页直接就能读到全部文档，无需再点进单独的文件。

用法：
    python tools/build_readme.py

说明：
    · README.md 是自动生成的，请不要手工编辑；改内容请改两份手册源文件。
      · 中文源文件：操作手册.md
      · 英文源文件：OPERATION_MANUAL_EN.md
    · 内联时会把手册里的标题整体降一级（H1→H2、H2→H3…），
      让 README 自己的标题保持唯一的 H1。**降级不影响锚点**，
      因为 GitHub 的锚点只取决于标题文字，与层级无关。
    · 代码块内的 # 注释行不会被误认为标题（已做围栏状态跟踪）。
"""

import os
import re
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

README_PATH = os.path.join(PROJECT_ROOT, "README.md")
ZH_SOURCE = "操作手册.md"
EN_SOURCE = "OPERATION_MANUAL_EN.md"

ZH_ANCHOR = "中文操作手册"
EN_ANCHOR = "english-operation-manual"

FENCE_RE = re.compile(r"^\s*(```|~~~)")
HEADING_RE = re.compile(r"^(#{1,6})(\s+)")


HEADER = """# EVE Online BR 战斗统计系统（通用版）

> 一个用于分析 **EVE Online** 战斗报告（BR）的本地统计工具：粘贴 BR 链接，自动汇总参战成员的
> **出击次数 / 击杀数 / 总伤害 / 使用舰船**，导出带柱状图的 Excel 报表；同时提供舰队**出勤统计**功能。
> 本仓库为**通用版本**，不含任何特定军团、联盟或个人的数据与标识。
>
> A local EVE Online battle-report analyser: paste BR links, get per-pilot **sorties / kills /
> damage / ships flown** aggregated into an Excel report with charts, plus a fleet
> **attendance tracker**. This is the **generic edition** — no corporation, alliance or
> personal data is bundled.

**🌐 文档 / Documentation**
[中文操作手册](#中文操作手册) · [English Operation Manual](#english-operation-manual) ·
[操作手册.md](操作手册.md) · [OPERATION_MANUAL_EN.md](OPERATION_MANUAL_EN.md) ·
[数据文件格式](data/README.md)

## 快速开始 / Quick start

```bash
pip install -r requirements.txt      # 安装依赖 / install dependencies
python app.py                        # 启动 / start (http://127.0.0.1:5000)
```

首次使用需在网页 **管理 → 军团管理** 添加你要统计的军团 ID；
其余配置集中在 [`config.py`](config.py)，源码中搜索 `TODO(通用版)` 或 `【需修改】` 即可定位全部待改项。

On first run, add the corporation you want to track under **管理 → 军团管理** in the web UI.
Everything else is configured in [`config.py`](config.py); search the source for
`TODO(通用版)` or `【需修改】` to find every option you may want to change.

| 模块 / Module | 说明 / Description |
| --- | --- |
| 战斗统计分析 | 解析多个 BR 链接，按军团筛选成员，统计出击/击杀/伤害/舰船 |
| 出勤统计分析 | 按活动逐次录入舰队成员，实时统计出勤次数并导出 Excel |
| 报表导出 | Excel 含数据表 + 「总伤害 Top10」「击杀数 Top10」两张柱状图 |
| 管理后台 | 军团管理 / 角色管理 / 历史报告 / 系统日志 |

其他命令 / Other commands：

```bash
python tools/smoke_test.py     # 冒烟测试（25 项断言，数据目录自动隔离）
python ship_id.py              # 更新舰船 ID→名称 映射（报表出现 Unknown 时用）
python build.py                # 打包 dist/BRStatisticsTool.exe
```

---

## 中文操作手册

"""

MIDDLE = """

---

## English Operation Manual

"""

FOOTER = """

---

<sub>
本 README 由 <code>tools/build_readme.py</code> 从 <a href="操作手册.md">操作手册.md</a> 与
<a href="OPERATION_MANUAL_EN.md">OPERATION_MANUAL_EN.md</a> 自动生成，请勿手工编辑——
修改文档请改上述两份源文件后重新执行该脚本。<br>
This README is generated by <code>tools/build_readme.py</code> from the two manual source
files above. Do not edit it by hand.
</sub>
"""


def demote_headings(text):
    """
    把 Markdown 标题整体降一级（H1→H2 …），代码围栏内的 # 注释不受影响。
    """
    out = []
    in_fence = False
    for line in text.split("\n"):
        if FENCE_RE.match(line):
            in_fence = not in_fence
            out.append(line)
            continue
        if not in_fence:
            m = HEADING_RE.match(line)
            if m and len(m.group(1)) < 6:
                line = "#" + line
        out.append(line)
    return "\n".join(out)


def to_inline_links(text):
    """
    手册里指向「另一份手册文件」的链接，在 README 内改成站内锚点，
    这样读者不用跳出去。指向其它文件的相对链接保持原样（在 GitHub 上可直接打开）。
    """
    text = text.replace(f"]({EN_SOURCE})", f"](#{EN_ANCHOR})")
    text = text.replace(f"]({ZH_SOURCE})", f"](#{ZH_ANCHOR})")
    return text


def read_source(filename):
    path = os.path.join(PROJECT_ROOT, filename)
    if not os.path.exists(path):
        print(f"[错误] 找不到源文件: {filename}")
        sys.exit(1)
    with open(path, encoding="utf-8") as f:
        return f.read()


def collect_slugs(text):
    """
    按 GitHub 规则计算所有标题锚点，用于检测跨语言重名标题导致的锚点冲突。
    """
    def slug(heading):
        s = heading.strip().lower()
        s = re.sub(r"[`*_]", "", s)
        s = "".join(ch for ch in s if ch.isalnum() or ch in " -_")
        return s.replace(" ", "-")

    slugs, in_fence = [], False
    for line in text.split("\n"):
        if FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if not in_fence:
            m = re.match(r"^#{1,6}\s+(.*)$", line)
            if m:
                slugs.append(slug(re.sub(r"\s+#+\s*$", "", m.group(1))))
    return slugs


def main():
    zh = to_inline_links(read_source(ZH_SOURCE))
    en = to_inline_links(read_source(EN_SOURCE))

    # 冲突检测：两个文档合到一起后可能出现同名标题
    all_slugs = collect_slugs(demote_headings(zh)) + collect_slugs(demote_headings(en))
    duplicates = {s for s in all_slugs if all_slugs.count(s) > 1}
    if duplicates:
        # 说明：同名标题会被 GitHub 自动加 -1 后缀，但**不影响任何链接**——
        # 手册里没有链接指向这些标题（它们只是 23.x / 附录 A.x 这类小节标题）。
        # 这里仅作提示，供需要完全唯一锚点时参考。
        print(f"提示：合并后有 {len(duplicates)} 个同名标题（GitHub 会自动加 -1 后缀，不影响链接）：")
        for d in sorted(duplicates):
            print(f"  · #{d}")
        print()

    readme = (
        HEADER
        + demote_headings(zh).strip()
        + MIDDLE
        + demote_headings(en).strip()
        + FOOTER
    )

    with open(README_PATH, "w", encoding="utf-8") as f:
        f.write(readme)

    size_kb = os.path.getsize(README_PATH) / 1024
    print(f"[OK] README.md 已生成  ({len(readme.splitlines())} 行, {size_kb:.1f} KB)")
    print(f"     中文正文 {len(zh.splitlines())} 行  +  英文正文 {len(en.splitlines())} 行")


if __name__ == "__main__":
    main()
